Link quids
ONSdigital/census-rm-load-generator pull request #6
Opened 2020-06-08 08:59 UTC by LukeLoze1

# Motivation and Context
New type qid linked event

# What has changed
Loads unlinked qids from DB
Create qid linked msg at random

# How to test?
Get some unlinked qids in the DB (running unaddress ATs good for this)
Run the load generator and check that some questionnaireLinked msgs are sent

# Links
https://trello.com/c/hGgjyuPz/994-load-generator-questionnaire-linked-8

2020-06-08 12:31 UTC, AdamHawtin requested changes
I think the readme needs updating

2020-06-08 12:39 UTC, ryangrundy7 approved these changes
Looks good! 👍

2020-06-09 07:44 UTC, AdamHawtin commented on README.md
> +(Config.UNADDRESSED_QIDS_TO_FETCH) number of unlinked qids from the database.
I think it's worth saying explicitly that a big enough sample load and unaddressed batch have to be run into the environment before running this.

2020-06-09 08:09 UTC, AdamHawtin approved these changes

2020-06-09 08:10 UTC, merged